### ISSUE TITLE
LED Button

### ISSUE THREAD

**Issue by Krocko** [artem-sedykh/mini-humidifier#1]
Hi. Thank you for this great plugin.
My humidifier has 3 values for the led brightness. 0 (bright), 1 (low), 2 (off).
Is it possible the get this? Maybe like the dropdown off the speed?
And would it be possible to display the name (with the option to rename) instead the icon?

**Comment by artem-sedykh** [comment]
Hello!
1. It’s not difficult for me to add a drop-down list for led, but is this necessary?) (add today, let it be)
2. Displaying the name in place of the icon is difficult, the plugin is designed to support mobile devices, if you have it then it will not fit in (

![image](https://user-images.githubusercontent.com/861063/79598794-34d1f180-80ed-11ea-9d9e-a798c393b283.png)

If you have design suggestions send pictures, we’ll be happy to discuss, but keep in mind that the access plugin is the same as for a mobile phone in the HA app

**Comment by Krocko** [comment]
Thank you for your fast response. 
For 1: now we have medium brightness (1) and led off (2). Would be nice if could change the brightness night low and day high. 
For 2: You are right. On a mobile device the names instead a button makes absolutely no sense.

**Comment by artem-sedykh** [comment]
Automation for brightness at night and during the day should be written in the Home Assistant see [automation ha](https://www.home-assistant.io/docs/automation/examples/) or use [appdaemon](https://www.home-assistant.io/docs/ecosystem/appdaemon/)

**Comment by artem-sedykh** [comment]
Released version v1.0.2, also updated the documentation
