### ISSUE TITLE
bug frontend HA 2022.11.*

### ISSUE THREAD

**Issue by vsimanin** [artem-sedykh/mini-humidifier#100]
![Снимок экрана 2022-11-08 215128](https://user-images.githubusercontent.com/9263449/200651218-2028f6f9-7721-4b4b-afe7-a6c8fef6f75d.png)
Привет! На версии 11 добавили скругленные края карточек. К сожалению, теперь карточка имеет квадратные края поверх скругленных.

**Comment by Olegz73** [comment]
Поддерживаю, появилось после обновления на 2022.11

**Comment by vsimanin** [comment]
Hello!? Fix please, bro 🤠

**Comment by regevbr** [comment]
I don't do ui. You are more than welcome to create a PR and contribute - "be the change you want to see in the world"

**Comment by SanchosPancho** [comment]
fixed in release 3.1.4 - https://github.com/artem-sedykh/mini-humidifier/pull/114
