### ISSUE TITLE
Border when embedded since 2022.11.0

### ISSUE THREAD

**Issue by Haronych** [artem-sedykh/mini-humidifier#105]
When the card is embedded in an entities card, there is a border around the **mini-humidifier** card.
Before HA 2022.11.0, there was no border.
**mini-climate-card** fixed in https://github.com/artem-sedykh/mini-climate-card/pull/109 and released under [2.4.2](https://github.com/artem-sedykh/mini-climate-card/releases/tag/v2.4.2)

**Comment by regevbr** [comment]
released in 3.1.2
