### ISSUE TITLE
Can you add a clean-mode button for zhimi.humidifier.ca1 or zhimi.humidifier.cb1?

### ISSUE THREAD

**Issue by Seonift** [artem-sedykh/mini-humidifier#107]
I need clean-mode for this model..

**Comment by regevbr** [comment]
Can you please paste here the attributes and state of your humidifier when clean mode is on and clean mode is of?

**Comment by Seonift** [comment]
I'll check it. But I don't know how to get attribute so it takes some times...

**Comment by regevbr** [comment]
Easily from the developer tools

![image](https://user-images.githubusercontent.com/5775519/210513888-deb2e097-c8b0-49ae-b96e-76f9c7dccbdd.png)

**Comment by Seonift** [comment]
@regevbr I'm sorry but where can I use xiaomi developer tools?

**Comment by Seonift** [comment]
It looks like doesn't appear... T.T
```
min_humidity: 30
max_humidity: 80
available_modes:
  - Silent
  - Medium
  - High
  - Auto
humidity: 80
mode: Auto
device_class: humidifier
friendly_name: humidifier
supported_features: 1
```

**Comment by regevbr** [comment]
are you sure you are looking at the actual device you are talking about?

**Comment by Seonift** [comment]
Yes its correct. `zhimi.humidifier.ca1`.
I can handle clean mode at mi home app.

**Comment by regevbr** [comment]
ok so nothing I can do here if the integration doesn't support it

**Comment by Seonift** [comment]
Ok thanks!
