### ISSUE TITLE
importNode is not a function

### ISSUE THREAD

**Issue by Anonym-tsk** [artem-sedykh/mini-humidifier#123]
Doesn't work at all.
Chrome 120.0.6099.129 (Mac, arm64)

![image](https://github.com/artem-sedykh/mini-humidifier/assets/1973755/49d568de-32d4-4bbf-ba30-e8de8e0d14e4)

**Comment by regevbr** [comment]
https://github.com/artem-sedykh/mini-climate-card/issues/137
You need to disable the chrome://flags/#enable-experimental-web-platform-features flag to fix it

**Comment by Anonym-tsk** [comment]
I think you should find which Chrome feature is breaking the plugin and fix your code. Because Google will release this feature someday.

**Comment by regevbr** [comment]
https://github.com/webcomponents/polyfills/issues/549
