### ISSUE TITLE
Support zhimi.humidifier.ca1

### ISSUE THREAD

**Issue by anhnvme** [artem-sedykh/mini-humidifier#13]
Hello,

Syssi had support zhimi.humidifier.ca1 at this repo https://github.com/syssi/xiaomi_airpurifier
Can you can check and support it ?

I'm tried add but not thing to show

Thanks

**Comment by artem-sedykh** [comment]
Added the ability to customize the plugin to configure other humidifiers. [v2.0.1](https://github.com/artem-sedykh/mini-humidifier/releases/tag/v2.0.1)
Read [readme](https://github.com/artem-sedykh/mini-humidifier/blob/master/README.md) file, there will be questions write to me.
