### ISSUE TITLE
'group: on' don’t work anymore with ha 0.113.0 beta

### ISSUE THREAD

**Issue by Krocko** [artem-sedykh/mini-humidifier#37]
Hello.
The option `group: on` don‘t work anymore with Home Assistant 0.113.0 beta.

**Comment by artem-sedykh** [comment]
Hi, i updated version to Home Assistant 0.113.0b3, displayed correctly:
![image](https://user-images.githubusercontent.com/861063/88179091-086dca00-cc34-11ea-8138-d2d35272672e.png)
can you add a screenshot?

**Comment by Krocko** [comment]
Oh sorry.
![image](https://user-images.githubusercontent.com/29394115/88199662-6bb42800-cc45-11ea-9ab4-fd8f3b4aae1f.jpeg)
![image](https://user-images.githubusercontent.com/29394115/88199676-6f47af00-cc45-11ea-8235-4c58b8f14a58.jpeg)
