### ISSUE TITLE
Жаль, но у меня не заработало

### ISSUE THREAD

**Issue by Silent4831** [artem-sedykh/mini-humidifier#38]
Я видел у вас внизу описание, что делать если не работает, но для кранов вроде меня, не понятно. В общем выдает такую ошибку. Если есть возможность помочь, буду признателен.
![2020-07-26_15-17-44](https://user-images.githubusercontent.com/37260995/88478815-de7a1780-cf53-11ea-939d-3384a82f2ee6.png)

**Comment by artem-sedykh** [comment]
Привет! напиши в телегу @anavrin72

вс, 26 июл. 2020 г. в 15:23, Silent4831 <notifications@github.com>:
