### ISSUE TITLE
Custom element doesn't exist: mini-humidifier.

### ISSUE THREAD

**Issue by olegkron** [artem-sedykh/mini-humidifier#40]
Done everything as on the Manual. 
The card is throwing this error: "Custom element doesn't exist: mini-humidifier."

![image](https://user-images.githubusercontent.com/47119689/90015315-1ce03800-dcb1-11ea-897a-9b950cce0c93.png)
![image](https://user-images.githubusercontent.com/47119689/90015333-25387300-dcb1-11ea-82ba-75eb3eda4739.png)
![image](https://user-images.githubusercontent.com/47119689/90015354-2a95bd80-dcb1-11ea-853c-36e459c46e8a.png)

**Comment by olegkron** [comment]
figured it out

**Comment by answer35** [comment]
Hi, i think I have the same issue but i don't know how to make it work. Can you help?

**Comment by flyjshum** [comment]
how fix it?
