### ISSUE TITLE
Work with humidifier domain

### ISSUE THREAD

**Issue by KTibow** [artem-sedykh/mini-humidifier#41]
Check out
https://github.com/home-assistant/core/pull/36759
It'd be nice if this card had native support for the humidifier domain.

**Comment by artem-sedykh** [comment]
fixed

**Comment by KTibow** [comment]
The README still needs to be updated.
> An entity_id from an entity within the fan domain.

**Comment by KTibow** [comment]
Huh. This isn't working:
![image](https://user-images.githubusercontent.com/10727862/103817356-655f1000-501b-11eb-8cf1-b5e3e6808d39.png)
Any ideas why?
