### ISSUE TITLE
Default configuration (model) documentation

### ISSUE THREAD

**Issue by slydiman** [artem-sedykh/mini-humidifier#49]
Please fix the documentation around available default configurations.
Probably the link `deerma.humidifier.mjjsq by @dedors [xiaomi_miio integration](https://www.home-assistant.io/integrations/xiaomi_miio)` is wrong. I don see any humidifier integrations at @dedors repositories.
https://www.home-assistant.io/integrations/xiaomi_miio simply does not support `deerma.humidifier.mjjsq`
The configuration `model: 'deerma.humidifier.mjjsq'` never worked for me.
The configuration `model: 'xiaomi_miio_airpurifier:deerma.humidifier.mjjsq'` works fine, but there is no any configuration sample in the documentation.
Note there is confusion between terms `model` and `default configuration`.

And the link [deerma.humidifier.mjjsq](https://github.com/artem-sedykh/mini-humidifier/blob/master/src/configurations/deerma_humidifier_mjjsq.js) is wrong too.

**Comment by BenTT85** [comment]
Thank you very much, I think this 2.3.2 will also fix my problem with my model " deerma.humidifier.jsq" which is also not supported by xiaomi_miio plugin.

Is it possible that the 2.3.2 version is not published yet?

https://github.com/artem-sedykh/mini-humidifier/releases/download/v2.3.2/mini-humidifier-bundle.js is not found.

Thank you for your support!

**Comment by artem-sedykh** [comment]
@BenTT85  [ 2.3.2 version](https://github.com/artem-sedykh/mini-humidifier/releases/tag/v2.3.2)  published
