### ISSUE TITLE
Mobile app HA android

### ISSUE THREAD

**Issue by fedor-smart** [artem-sedykh/mini-humidifier#51]
Добрый день. Спасибо за твою работу, карточка мне очень понравилась. В браузере все работает, а вот в мобильном приложении на андроиде такая ошибка : "Custom element doesn't exist: mini-humidifier" . Я предполагаю что проблема в пути который указывается в resources:   - url: . Было тоже самое и в браузере, пока не поправил как написано в инструкции при установке (но в приложении, к сожалению, эту проблема не ушла). Подскажи, пожалуйста, своим советом.

Good afternoon. Thank you for your work, I really liked this card. In the browser, everything works, but in the mobile app on android, this error : "Custom element doesn't exist: mini-humidifier" . I assume that the problem is in the path that is specified in resources: - url: . It was the same in the browser, until I corrected it as it is written in the installation instructions (but in the application, unfortunately, this problem did not go away). Tell me, please, with your advice.

**Comment by artem-sedykh** [comment]
Привет! проблема осталась? если нужна помощь в настройке пиши в телегу anavrin72, сорри за долгий ответ

**Comment by fedor-smart** [comment]
На новой версии андроида(на 10 и выше) все работает, а на старой (5.1) - все та же ошибка. Не знаю в чем причина. Увидел обнову и новую инструкцию. Попробую по ней сделать. Спасибо за ответ.
