### ISSUE TITLE
Button color

### ISSUE THREAD

**Issue by Krocko** [artem-sedykh/mini-humidifier#6]
I think it would be better than
`mini-humidifier-button-color` also has default `var(--paper-item-icon-color)`
![A825B248-F231-413D-B03A-2029FF41FB94](https://user-images.githubusercontent.com/29394115/79680739-5cbb7500-8213-11ea-98ae-ba4394f5b0ec.jpeg)

**Comment by artem-sedykh** [comment]
Hello, thanks for your feedback!
Is that what you want?
```--mh-button-color: var(--mini-humidifier-button-color, var(--paper-item-icon-color, #44739e));```

**Comment by Krocko** [comment]
Yes

**Comment by artem-sedykh** [comment]
closed.
[release  v1.0.4](https://github.com/artem-sedykh/mini-humidifier/releases/tag/v1.0.4)
