### ISSUE TITLE
After upgrading HASS to 2021.8 it doesn't work anymore

### ISSUE THREAD

**Issue by Stimpy68** [artem-sedykh/mini-humidifier#66]
Dashobaords on which I have the card don't load anymore, these errors occur in the logs:

021-08-07 11:38:38 ERROR (MainThread) [frontend.js.latest.202108040] http://homeassistant.local:8123/hacsfiles/mini-humidifier/mini-humidifier-bundle.js:1:67826 Uncaught TypeError: Cannot read property 'id' of undefined
2021-08-07 11:39:00 ERROR (MainThread) [frontend.js.latest.202108040] http://homeassistant.local:8123/hacsfiles/mini-humidifier/mini-humidifier-bundle.js:1:67826 Uncaught TypeError: Cannot read property 'id' of undefined

Removed the integration for now, and dashboards work again.

Maybe something to do with the breaking change:

**Xiaomi Miio
Existing Xiaomi Mi automations using the platform specific services for humidifiers will have a breaking change. You need to change their automation to use new services. Existing fan entities will be automatically replaced with new humidity entities.

The entity name is migrated from the fan entity name. The fan entity_id will change because the platform will change.

For the related entities the old fan entity name will be prepended to the new entities.

Example:

Entity with entity_id “fan.my_device” and name “My humidifier” will migrate to an entity with entity_id “humidifier.my_humidifier” and name “My humidifier”.

A sensor for humidity will have a name like “My humidifier Humidity”.

(@jbouwh - #52366) (xiaomi_miio docs)**

**Comment by Krocko** [comment]
Same here. @artem-sedykh can you please have a look?

**Comment by jbouwh** [comment]
The fan entity was removed and replaced by a humidifier entity. You can find it and sensors at settings-> entities

**Comment by vsimanin** [comment]
Same problem.  Can't get this to work again:(

**Comment by artem-sedykh** [comment]
New integration is still in development and not tested well, water sensor still missing.  
Added an example for calculating the water level for [cb1](https://github.com/home-assistant/core/issues/54153#issuecomment-896081036)

**Comment by cpuks** [comment]
Change of entity to new one - humidifier.xxxx doesn't solve issue in my case. I've got two CB1 and can't get them to work with this card anymore

**Comment by kirbo** [comment]
Any updates or workarounds on this? My humidifiers haven't worked in weeks, ever since I updated to 2021.8.. I'd like to make these somehow working.

**Comment by artem-sedykh** [comment]
Fixed
