### ISSUE TITLE
Проблема с выпадающим списком

### ISSUE THREAD

**Issue by Villi342** [artem-sedykh/mini-humidifier#79]
Добрый день! Выпадающие списки развернуты. подскажите пожалуйста как исправить.
![01](https://user-images.githubusercontent.com/77030729/156725382-0688c305-9a65-4b6b-b1de-56ba2d15a130.jpg)

**Comment by vsimanin** [comment]
Поддерживаю, проблема появилась с новой версией 2022.3.0, поправьте пожалуйста;)

**Comment by Olegz73** [comment]
Поддерживаю, такая же проблема на 2022.3.0

**Comment by regevbr** [comment]
To use the fix I made, until it is released, follow the steps I made [here](https://gist.github.com/regevbr/4e91349b63f1a0700f312ce34dbad233)
