### ISSUE TITLE
TypeError: Illegal constructor

### ISSUE THREAD

**Issue by earthpyy** [artem-sedykh/mini-humidifier#86]
Hi, I'm having a trouble enabling the plugin:

<img width="500" alt="ภาพ" src="https://user-images.githubusercontent.com/5132475/160445439-c73b8dbd-0ee7-4209-9984-66664c0322d1.png">

## Info

Plugin version: 3.0.2  
Browser: Firefox Developer Edition 99.0b8

## Server Logs

```
Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190
First occurred: 11:25:22 PM (32 occurrences)
Last logged: 11:34:37 PM

https://xxx/hacsfiles/mini-humidifier/mini-humidifier-bundle.js?hacstag=253019926302:1:2046 TypeError: Illegal constructor.
```

**Comment by earthpyy** [comment]
Sorry, my mistake. Will re-open the issue if the problem still occur.

**Comment by regevbr** [comment]
@earthpyy what was the issue? I just installed the beta to test it :-(

**Comment by earthpyy** [comment]
> @earthpyy what was the issue? I just installed the firefox beta version to replciate it :-(

@regevbr First of all, thanks for your quick response!

The problem was I didn't use v2022.3+ HA as specified in the README. After upgraded, everything seems fine.

BTW, before it was fixed, I tried to downgrade the plugin to v2.x.x and the problem still occur.

**Comment by regevbr** [comment]
strange, from what I can dig up it should not happen. I just tried downgrading to 2.x and it doesn't happen. (I'm not downgrading my ha though :-) ) in any case as long as the latest works I'm clam :-)

**Comment by earthpyy** [comment]
Cool!
