### ISSUE TITLE
deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by malendure81** [artem-sedykh/mini-humidifier#88]
hello, could you integrate deerma.humidifier.jsq5 ?
![Screenshot 2022-05-24 08 10 43](https://user-images.githubusercontent.com/75225135/169961195-358f01f9-d74c-4a41-8cd8-1d81feacada5.png)

thanks

**Comment by regevbr** [comment]
I don't have that purifier and as such, I can't do it... You can create your own custom configuration and then send it over and I will be happy to integrate it
