### ISSUE TITLE
TypeError: Illegal constructor

### ISSUE THREAD

**Issue by dnaboko** [artem-sedykh/mini-humidifier#90]
Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190 
First occurred: 12:00:00 (6 occurrences) 
Last logged: 12:04:01

http://192.168.1.50:8123/local/community/mini-humidifier/mini-humidifier-bundle.js?v=2.5.5:1:2046 Uncaught TypeError: Illegal constructor
http://192.168.1.50:8123/local/community/mini-humidifier/mini-humidifier-bundle.js:1:2071 TypeError: Illegal constructor

Using mini-humidifier-bundle.js?v=3.0.3
Home Assistant 2022.2.3

**Comment by regevbr** [comment]
![Screenshot_2022-05-28-22-43-24-95_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/5775519/170840620-17dc0307-20e7-4876-b55f-eac3b9018a57.jpg)
